### PR TITLE
bump binutils

### PR DESCRIPTION
**Pull request by anatol**

### CODE REVIEW

**Comment by anatol** [comment]
It turned out that my guile-2.0 compat patch does not work at Ubuntu. Ubuntu still has the old guile package. I dropped my patch until I find a better way to detect the system guile version.

**Comment by travisg** [comment]
Yeah I was meaning to try it, since the fixed revision of guile seems to be a compatibility thing.

**Comment by travisg** [comment]
hopefully will get to this today: i have a few test cases i run on my end building this for a pile of architectures on a variety of host oses.

**Comment by anatol** [comment]
sgtm, Travis.

I put guile to a separate branch in case if you want to look at it https://github.com/anatol/toolchains/commit/21ce0f97f2da5d48a2ff56d6e054fb8fc084980e

**Comment by travisg** [comment]
tested locally, seems to work great.

**Pull request merged**
